language: java

# use the container based infrastructure on travis
sudo: false

# enable cache to stop downloading all maven plugins every time
cache:
  directories:
    - $HOME/.m2/repository

# No need to run mvn install, so we use this step to print env details instead
install: mvn --version

# the package phase is all we need. deploy/install is skipped
script: mvn clean verify javadoc:javadoc

jdk:
  - oraclejdk8

notifications:
  email:
    - gcviewer@gmx.ch
